"""Run only SPICE in a constrained local Docker container, not entrant Python."""
import os
import re
import shutil
import subprocess
import uuid


class ContainerBackend:
    def __init__(self, image):
        self.docker = shutil.which("docker")
        if not self.docker:
            raise ValueError("Docker is required for --docker-image")
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_./:@-]*", image):
            raise ValueError("invalid Docker image name or digest")
        result = subprocess.run([self.docker, "image", "inspect", "--format", "{{.Id}}", image],
                                capture_output=True, text=True, timeout=15)
        if result.returncode:
            raise ValueError("Docker image is not available locally; build competition/container/Dockerfile first")
        self.image_id = result.stdout.strip()
        if not re.fullmatch(r"sha256:[0-9a-f]{64}", self.image_id):
            raise ValueError("Docker did not return an immutable image ID")
        self.name = "spicenn2-simulator-" + uuid.uuid4().hex
        uid = os.getuid() if hasattr(os, "getuid") else 65534
        gid = os.getgid() if hasattr(os, "getgid") else 65534
        if uid == 0:
            raise ValueError("run isolated scoring as a non-root host user")
        self.base = [self.docker, "run", "--rm", "--pull=never", "--network=none",
                     "--read-only", "--cap-drop=ALL", "--security-opt=no-new-privileges",
                     "--user", f"{uid}:{gid}", "--pids-limit=64", "--cpus=2",
                     "--memory=4g", "--memory-swap=4g", "--ulimit", "fsize=2147483648:2147483648",
                     "--tmpfs", "/tmp:rw,noexec,nosuid,nodev,size=128m",
                     "--entrypoint", "/opt/ngspice/bin/ngspice"]

    def version(self):
        result = subprocess.run(self.base + [self.image_id, "--version"], capture_output=True,
                                text=True, check=True, timeout=15)
        return result.stdout.strip()

    def create_command(self, work):
        # Only this freshly generated simulator directory is exposed. No source
        # checkout, dataset archive, labels, home directory or Docker socket.
        return self.base[:1] + ["create"] + self.base[2:] + [
            "--name", self.name, "--mount", f"type=bind,src={work.resolve()},dst=/work",
            "--workdir", "/work", self.image_id, "-n", "-b", "harness.cir"]

    def command(self, work):
        # Create synchronously before applying the simulation timeout. Otherwise
        # a killed `docker run` client can race a still-pending create request.
        result = subprocess.run(self.create_command(work), capture_output=True,
                                text=True, check=True, timeout=30)
        identifier = result.stdout.strip()
        if not re.fullmatch(r"[0-9a-f]{64}", identifier):
            raise RuntimeError("Docker did not return a container ID")
        return [self.docker, "start", "--attach", identifier]

    def cancel(self):
        # Killing the Docker client does not necessarily kill its container.
        # This name is generated by us, not taken from a submission or trace.
        result = subprocess.run([self.docker, "rm", "--force", self.name],
                                capture_output=True, text=True, timeout=15)
        if result.returncode and "No such container" not in result.stderr:
            raise RuntimeError(f"could not stop container {self.name}: {result.stderr.strip()}")
