#!/usr/bin/env python3
"""Export the DIRECT multiclass delta-rule circuit as a runner submission.

Adapted from experiments/gen_mc.py: differential current readout and five-MOS
error/input-gated update cell. Adds physical reset and learning-enable switches.
No dataset is read and no weights are trained by this generator.
"""
import argparse
from pathlib import Path


def circuit(inputs, labels, capacitance=1.67e-6):
    lines = ["* Analog delta-rule learner: generated by competition/make_baseline.py",
             "* Weight = capacitor voltage; update current depends on error and input.",
             "* Based on the DIRECT path of experiments/gen_mc.py."]
    def emit(line):
        lines.append(line)
    for c in labels:
        cp, cn, mirror, error = (f"n_{x}{c}" for x in ("pos", "neg", "mirror", "error"))
        # Convert the difference of positive/negative synapse currents to a score.
        for name, d, g, s, model, width in [
            ("a", cn, cn, "0", "nch", 20),
            ("b", f"out{c}", cn, "0", "nch", 20),
            ("c", cp, cp, "0", "nch", 20),
            ("d", mirror, cp, "0", "nch", 20),
            ("e", mirror, mirror, "vdd", "pch", 60),
            ("f", f"out{c}", mirror, "vdd", "pch", 60),
            ("ep", error, mirror, "vdd", "pch", 60),
            ("en", error, cn, "0", "nch", 20),
            ("off", error, "voffset", "vdd", "pch", 10),
            ("target", error, f"target{c}", "0", "nch", 10),
        ]:
            emit(f"M{name}{c} {d} {g} {s} {s} {model} W={width}u L=1u")
        emit(f"Rscore{c} out{c} vref 7k")
        emit(f"Rerror{c} {error} verror 7k")
        for i, signal in enumerate([f"in{k}" for k in range(inputs)] + ["vbias"]):
            tag = f"{c}_{i}"
            weight, tail, mirror_up, gate = (f"n_{x}{tag}" for x in ("w", "tail", "up", "gate"))
            emit(f"* Synapse class={c}, input={signal}; {weight} stores the learned weight.")
            emit(f"Cw{tag} {weight} 0 {capacitance:.8g}")
            emit(f"Mreset{tag} vweight reset {weight} 0 syn W=1000u L=1u")
            emit(f"Mpos{tag} {signal} {weight} {cp} 0 syn W=10u L=1u")
            emit(f"Mneg{tag} {signal} vweight {cn} 0 syn W=10u L=1u")
            # Input modulates the update cell's tail current. The error steers
            # that current into or out of the weight capacitor (analog delta rule).
            emit(f"Menable{tag} {gate} learn 0 0 nch W=1000u L=1u")
            emit(f"Mtail{tag} {tail} {signal} {gate} 0 nch W=20u L=1u")
            emit(f"Mu1_{tag} {mirror_up} verror {tail} 0 nch W=20u L=1u")
            emit(f"Mu2_{tag} {weight} {error} {tail} 0 nch W=20u L=1u")
            emit(f"Mu3_{tag} {mirror_up} {mirror_up} vdd vdd pch W=60u L=1u")
            emit(f"Mu4_{tag} {weight} {mirror_up} vdd vdd pch W=60u L=1u")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--inputs", type=int, choices=range(1, 17), default=16)
    parser.add_argument("--labels", default="0,1,7")
    args = parser.parse_args()
    labels = [int(x) for x in args.labels.split(",")]
    if not labels or len(set(labels)) != len(labels) or any(x not in range(10) for x in labels):
        parser.error("labels must be distinct integers in 0..9")
    with args.output.open("x") as output:
        output.write(circuit(args.inputs, labels))


if __name__ == "__main__":
    main()
